### ISSUE TITLE
Swift 3 Compatibility

### ISSUE THREAD

**Issue by tonymuu** [omergul123/LLSimpleCamera#115]
Hi, I just updated to Xcode 8 and Swift 3 yesterday, and I'm getting a lot of "Ambiguous use of" errors, specifically with the enums such as "LLCameraPositionFront", and "LLCameraFlashOff", etc. Also, the onError method's error parameter can't find its property domain or code.. the code example I've been using https://github.com/strawb3rryx7/LLSimpleCamera-Swift-Example is now broken... Would you be able to add Swift 3 Compatibility anytime soon? Thanks. The image is here: http://i.imgur.com/T9F6H9P.png

**Comment by akovalov** [comment]
@tonymuu please check your project settings. Your "Ambiguous use of" error could be due to wrong setup. I'm using it in Swift 3 project and everything is fine. This project is written in Objective-C so I believe it does not need any Swift 3 compatibility code changes. Hope this helps.

**Comment by tonymuu** [comment]
I reverted back to Swift 2.3 for now. I'll keep this in mind though. Thanks!
