### ISSUE TITLE
Square

### ISSUE THREAD

**Issue by filipandrei87** [omergul123/LLSimpleCamera#19]
How can wee get a square photo (Instagram)?
Or maybe add an "edit" step as in camera app?

**Comment by omergul123** [comment]
You can easily set the camera size with method:
[self.camera attachToViewController:self withFrame:CGRectMake(0, 0, screenRect.size.width, screenRect.size.height)];

Simple specify your desired width and height.

**Comment by kafejo** [comment]
Not entirely true. You have to set self.camera.view.frame as well.
```
[self.camera attachToViewController:self withFrame:CGRectMake(0, 0, screenRect.size.width, screenRect.size.width)];
self.camera.view.frame = CGRectMake(0, 0, screenRect.size.width, screenRect.size.width);
```
Otherwise it keeps in fullscreen.

**Comment by rad182** [comment]
I tried the code above but still doesn't work. still fullscreen currently testing iOS 8.4 iPhone 6

**Comment by youwebny** [comment]
I am unable to resize the camera view with either of those methods on iOS 8.2

**Comment by holahyunsik** [comment]
How about square video? For photos it does work but for videos I don't think so.
