### ISSUE TITLE
Adding overlayview from storyboard

### ISSUE THREAD

**Issue by howkuen** [omergul123/LLSimpleCamera#23]

**Comment by howkuen** [comment]
Hi,
I was trying to user your lib to add custom overlay to a camera view with use of storyboards instead of writing the components code. I had some trouble with the camera view going in front of my storyboard components.
I made a slight change in your lib to fix this:

in attachToViewController method
changed [vc.view addSubview: self.view] with
[vc.view insertSubview:self.view atIndex:0];

same with self.preview view

Note that still I had to reassign images for image components (uiimageview, uibutton) after attaching camera vc to view controller - still don't know why? 
Any clues ?

**Comment by besi** [comment]
@howkuen 

I do the same thing. I have a `cropOverlay` which I need to bring to front, whenever I start the camera:

```swift
    // Inside my CameraViewController

    @IBOutlet weak var cropOverlay: UIView!

    func startCamera(){
        camera.start()
        view.bringSubviewToFront(cropOverlay)
    }
```
