### ISSUE TITLE
Zoom Out

### ISSUE THREAD

**Issue by aykutt** [omergul123/LLSimpleCamera#24]
Hi, Thanks for sharing,

Rear camera is seems like zoomed. 
I checked with native iphone cam (with fasten the phone) from same distance in square mode. And native cam view angle is more wide. Is there any zoom value?

Thanks

**Comment by omergul123** [comment]
Yep, its because I use the following piece to make sure the camera fills the given frame:
```
captureVideoPreviewLayer.videoGravity = AVLayerVideoGravityResizeAspectFill;
```
If you change **AVLayerVideoGravityResizeAspectFill** to **AVLayerVideoGravityResizeAspectFit**, it won't zoom but also it won't fill the screen.
