### ISSUE TITLE
Torch/flash not working (iOS 8)

### ISSUE THREAD

**Issue by lucasmoreira** [omergul123/LLSimpleCamera#25]
Hello guys.

I couldn't make flash/torch work on iOS 8.
I tried to turn the flash on in both my own project and LLSimpleCamera's example and it didn't work neither.

I tried to workaround as well but I didn't got any success.

Anybody notice that?

Thanks.

**Comment by omergul123** [comment]
@lucasmoreira  please check with the newly update version. It should work.

**Comment by cyril94440** [comment]
This is still not working for me
iOS 8 iPhone 6.

Too bad, the controller is awesome :)

**Comment by cyril94440** [comment]
Working, mea culpa

**Comment by omergul123** [comment]
@cyril94440 what was the problem?

**Comment by cyril94440** [comment]
Though that the flash was supposed to trigger directly not at shoot time ... Shame on me

**Comment by omergul123** [comment]
@cyril94440 Yep torch and flash are separate things. Flash is meant for photo capturing, and torch for video taking. I will be adding video future in couple of weeks and torch option will be available too.

**Comment by cyril94440** [comment]
Thanks for the infos !
Awesome, can't wait ;)
