### ISSUE TITLE
Camera display orientation issue

### ISSUE THREAD

**Issue by pukeanddie** [omergul123/LLSimpleCamera#26]
In the example project, if I select to enable all orientations, the camera display properly flips. If present homeViewController within my app, the orientations are behaving strangely. After the first orientation change the axis are all messed up. I am assuming this isn't a bug in your library, but any hints as to what might be different about my project that could be causing this to happen?

**Comment by omergul123** [comment]
@pukeanddie Laying out the camera view is on your responsibility. You can use the parent view controller's viewWillLayoutSubviews method to re-set the camera view frame. Or you can use AutoLayout.
