### ISSUE TITLE
setOnError on Swift 

### ISSUE THREAD

**Issue by kevinnguy** [omergul123/LLSimpleCamera#82]
Does anyone know how to set `onError` on Swift? I know in Objective-C, you can do:

```
[self.camera setOnError:^(LLSimpleCamera *camera, NSError *error) {
    // Something
}];
```

but on Swift, I don't have access to `setOnError`. I tried doing:

```
self.camera.onError = ({(camera : LLSimpleCamera!, error : NSError!) -> Void! in 
    // Something
})
```

but I would get an error. I just started working with Swift so this might be a syntax issue. Thanks for the great library and for the help!

**Comment by strawb3rryx7** [comment]
Look at my repository for LLSimpleCamera on Swift.

**Comment by kevinnguy** [comment]
Thanks for the help @strawb3rryx7 ! Been learning Swift and so far, so good!

**Comment by kevinnguy** [comment]
This is how it can be done on Swift:

```
self.camera.onError = {(camera, error) -> Void in
    // Something
}
```

**Comment by strawb3rryx7** [comment]
Keep coding mate! 👍🏼
