### ISSUE TITLE
Quick flash of photo in opposite orientation

### ISSUE THREAD

**Issue by LeenaMansour** [omergul123/LLSimpleCamera#9]
When using LLSimpleCamera (the example project or my own implementation of it) after capturing a photo I see a quick flash of the image in the opposite orientation before the imageViewController shows up. So if the device is in portrait mode when I take the photo, I very quickly see a flash of that image in landscape mode and then it goes into portrait again when the imageviewcontroller.

In my implementation, when I dismiss the imageviewcontroller followed by the camera one I see that sideways flash again quick.
Not sure if you're seeing the same thing.

**Comment by omergul123** [comment]
Could you give more info? Which orientation are you capturing the photo, and which iOS version? @LeenaMansour

**Comment by omergul123** [comment]
Fixed with version 2.1.0.
